Factor git-ls-tree calls into _git_ls_tree.

diff --git a/bin/fpf-check b/bin/fpf-check
--- a/bin/fpf-check
+++ b/bin/fpf-check
@@ -49,7 +49,20 @@ export GIT_WORK_TREE="$PREFIX"
 # the package.
 COMMIT="$(git rev-parse "HEAD")"
 TREE="$(git show --pretty="format:%T" "$COMMIT" | head -n1)"
-_verify_mode "$TREE" "" >>"$TMP"
+_git_ls_tree "$TREE" | while read MODE TYPE SHA PATHNAME
+do
+	L_MODE="$(echo -n "$MODE" | tail -c4)"
+	P_MODE="$(_mode "$PREFIX/$PATHNAME" 2>"/dev/null" || true)"
+	if [ -z "$P_MODE" ]
+	then
+		echo "fpf: $PREFIX/$PATHNAME is missing" >&2
+		echo 1
+	elif [ -n "$L_MODE" -a "$L_MODE" != "$P_MODE" ]
+	then
+		echo "fpf: $PREFIX/$PATHNAME mode is $P_MODE, should be $L_MODE" >&2
+		echo 1
+	fi
+done >"$TMP"
 
 # Verify that none of the installed files have been changed from their
 # packaged versions.
